export const GENERATE_PREV_BLOCKCHAIN = 'GENERATE_PREV_BLOCKCHAIN';
export const MINE_NONCE_PREV_BLOCKCHAIN = 'MINE_NONCE_PREV_BLOCKCHAIN';
export const MODIFY_PREV_BLOCKCHAIN = 'MODIFY_PREV_BLOCKCHAIN';
