export const GENERATE_PREV_BLOCKCHAIN = 'GENERATE_PREV_BLOCKCHAIN';
export const MINE_NONCE_PREV_BLOCKCHAIN = 'MINE_NONCE_PREV_BLOCKCHAIN';
export const MODIFY_PREV_BLOCKCHAIN = 'MODIFY_PREV_BLOCKCHAIN';
export const SET_MINING_PREV_BLOCK = 'SET_MINING_PREV_BLOCK';

export const GENERATE_PREV_BLOCKCHAIN_PEER_B = 'GENERATE_PREV_BLOCKCHAIN_PEER_B';
export const MINE_NONCE_PREV_BLOCKCHAIN_PEER_B = 'MINE_NONCE_PREV_BLOCKCHAIN_PEER_B';
export const MODIFY_PREV_BLOCKCHAIN_PEER_B = 'MODIFY_PREV_BLOCKCHAIN_PEER_B';
export const SET_MINING_PREV_BLOCK_PEER_B = 'SET_MINING_PREV_BLOCK_PEER_B';

export const GENERATE_PREV_BLOCKCHAIN_PEER_C = 'GENERATE_PREV_BLOCKCHAIN_PEER_C';
export const MINE_NONCE_PREV_BLOCKCHAIN_PEER_C = 'MINE_NONCE_PREV_BLOCKCHAIN_PEER_C';
export const MODIFY_PREV_BLOCKCHAIN_PEER_C = 'MODIFY_PREV_BLOCKCHAIN_PEER_C';
export const SET_MINING_PREV_BLOCK_PEER_C = 'SET_MINING_PREV_BLOCK_PEER_C';

export const GENERATE_TOKEN_BLOCKCHAIN = 'GENERATE_TOKEN_BLOCKCHAIN';
export const MINE_NONCE_TOKEN_BLOCKCHAIN = 'MINE_NONCE_TOKEN_BLOCKCHAIN';
export const MODIFY_TOKEN_BLOCKCHAIN = 'MODIFY_TOKEN_BLOCKCHAIN';
export const SET_MINING_TOKEN_BLOCK = 'SET_MINING_TOKEN_BLOCK';
